
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action pasteAction;
	
	private global::Gtk.Action yesAction;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.HPaned paned;
	
	private global::Gtk.VBox vbox5;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TreeView tblPorts;
	
	private global::Gtk.HBox hbox8;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Label lblPuerto;
	
	private global::Gtk.Image imgPortStatus;
	
	private global::Gtk.Button btndisconnect;
	
	private global::Gtk.Button btnconnect;
	
	private global::Gtk.VBox vbox6;
	
	private global::Gtk.HBox hbox9;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.ComboBoxEntry cmbBaudRate;
	
	private global::Gtk.HBox hbox10;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.ComboBoxEntry cmbParity;
	
	private global::Gtk.HBox hbox11;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.ComboBoxEntry cmbDatabits;
	
	private global::Gtk.HBox hbox12;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.ComboBoxEntry cmbStopbits;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TreeView tblBitacora;
	
	private global::Gtk.Statusbar statusbar;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.pasteAction = new global::Gtk.Action ("pasteAction", global::Mono.Unix.Catalog.GetString ("Configuraciones"), null, "gtk-paste");
		this.pasteAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Configuraciones");
		w1.Add (this.pasteAction, "<Primary><Alt>c");
		this.yesAction = new global::Gtk.Action ("yesAction", global::Mono.Unix.Catalog.GetString ("Autoconectar"), null, "gtk-yes");
		this.yesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Autoconectar");
		w1.Add (this.yesAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.BorderWidth = ((uint)(6));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar1\'><menu name=\'pasteAction\' action=\'pasteAction\'><menui" +
		"tem name=\'yesAction\' action=\'yesAction\'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox4.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.paned = new global::Gtk.HPaned ();
		this.paned.CanFocus = true;
		this.paned.Name = "paned";
		this.paned.Position = 320;
		this.paned.BorderWidth = ((uint)(1));
		// Container child paned.Gtk.Paned+PanedChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.WidthRequest = 38;
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.tblPorts = new global::Gtk.TreeView ();
		this.tblPorts.CanFocus = true;
		this.tblPorts.Name = "tblPorts";
		this.GtkScrolledWindow.Add (this.tblPorts);
		this.vbox5.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.GtkScrolledWindow]));
		w4.Position = 0;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 10;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"black\" size=\"large\">Puerto</span>");
		this.label3.UseMarkup = true;
		this.hbox8.Add (this.label3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label3]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.lblPuerto = new global::Gtk.Label ();
		this.lblPuerto.Name = "lblPuerto";
		this.lblPuerto.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"black\" size=\"xx-large\" weight=\"bold\">DATA PORT</span>");
		this.lblPuerto.UseMarkup = true;
		this.hbox8.Add (this.lblPuerto);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.lblPuerto]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.imgPortStatus = new global::Gtk.Image ();
		this.imgPortStatus.Name = "imgPortStatus";
		this.imgPortStatus.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-no", global::Gtk.IconSize.Button);
		this.hbox8.Add (this.imgPortStatus);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.imgPortStatus]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.btndisconnect = new global::Gtk.Button ();
		this.btndisconnect.CanFocus = true;
		this.btndisconnect.Name = "btndisconnect";
		this.btndisconnect.UseUnderline = true;
		global::Gtk.Image w8 = new global::Gtk.Image ();
		w8.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-connect", global::Gtk.IconSize.Button);
		this.btndisconnect.Image = w8;
		this.hbox8.Add (this.btndisconnect);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.btndisconnect]));
		w9.PackType = ((global::Gtk.PackType)(1));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.btnconnect = new global::Gtk.Button ();
		this.btnconnect.CanFocus = true;
		this.btnconnect.Name = "btnconnect";
		this.btnconnect.UseUnderline = true;
		global::Gtk.Image w10 = new global::Gtk.Image ();
		w10.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-disconnect", global::Gtk.IconSize.Button);
		this.btnconnect.Image = w10;
		this.hbox8.Add (this.btnconnect);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.btnconnect]));
		w11.PackType = ((global::Gtk.PackType)(1));
		w11.Position = 4;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox5.Add (this.hbox8);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox8]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.Xpad = 20;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Baud Rate:");
		this.hbox9.Add (this.label5);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label5]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.cmbBaudRate = global::Gtk.ComboBoxEntry.NewText ();
		this.cmbBaudRate.AppendText (global::Mono.Unix.Catalog.GetString ("9600"));
		this.cmbBaudRate.Name = "cmbBaudRate";
		this.cmbBaudRate.Active = 0;
		this.hbox9.Add (this.cmbBaudRate);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.cmbBaudRate]));
		w14.Position = 1;
		this.vbox6.Add (this.hbox9);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox9]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		w15.Padding = ((uint)(4));
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.Xpad = 31;
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Parity:");
		this.hbox10.Add (this.label6);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label6]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.cmbParity = global::Gtk.ComboBoxEntry.NewText ();
		this.cmbParity.AppendText (global::Mono.Unix.Catalog.GetString ("Even"));
		this.cmbParity.AppendText (global::Mono.Unix.Catalog.GetString ("Odd"));
		this.cmbParity.AppendText (global::Mono.Unix.Catalog.GetString ("None"));
		this.cmbParity.AppendText (global::Mono.Unix.Catalog.GetString ("Mark"));
		this.cmbParity.AppendText (global::Mono.Unix.Catalog.GetString ("Space"));
		this.cmbParity.Name = "cmbParity";
		this.cmbParity.Active = 2;
		this.hbox10.Add (this.cmbParity);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.cmbParity]));
		w17.Position = 1;
		this.vbox6.Add (this.hbox10);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox10]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.Xpad = 24;
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Databits:");
		this.hbox11.Add (this.label7);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label7]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.cmbDatabits = global::Gtk.ComboBoxEntry.NewText ();
		this.cmbDatabits.AppendText (global::Mono.Unix.Catalog.GetString ("4"));
		this.cmbDatabits.AppendText (global::Mono.Unix.Catalog.GetString ("5"));
		this.cmbDatabits.AppendText (global::Mono.Unix.Catalog.GetString ("6"));
		this.cmbDatabits.AppendText (global::Mono.Unix.Catalog.GetString ("7"));
		this.cmbDatabits.AppendText (global::Mono.Unix.Catalog.GetString ("8"));
		this.cmbDatabits.Name = "cmbDatabits";
		this.cmbDatabits.Active = 4;
		this.hbox11.Add (this.cmbDatabits);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.cmbDatabits]));
		w20.Position = 1;
		this.vbox6.Add (this.hbox11);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox11]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox ();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.Xpad = 24;
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Stopbits:");
		this.hbox12.Add (this.label8);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label8]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.cmbStopbits = global::Gtk.ComboBoxEntry.NewText ();
		this.cmbStopbits.AppendText (global::Mono.Unix.Catalog.GetString ("None"));
		this.cmbStopbits.AppendText (global::Mono.Unix.Catalog.GetString ("One"));
		this.cmbStopbits.AppendText (global::Mono.Unix.Catalog.GetString ("OnePointFive"));
		this.cmbStopbits.AppendText (global::Mono.Unix.Catalog.GetString ("Two"));
		this.cmbStopbits.Name = "cmbStopbits";
		this.cmbStopbits.Active = 3;
		this.hbox12.Add (this.cmbStopbits);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.cmbStopbits]));
		w23.Position = 1;
		this.vbox6.Add (this.hbox12);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox12]));
		w24.Position = 3;
		w24.Expand = false;
		w24.Fill = false;
		this.vbox5.Add (this.vbox6);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vbox6]));
		w25.Position = 2;
		w25.Expand = false;
		w25.Fill = false;
		this.paned.Add (this.vbox5);
		global::Gtk.Paned.PanedChild w26 = ((global::Gtk.Paned.PanedChild)(this.paned [this.vbox5]));
		w26.Resize = false;
		// Container child paned.Gtk.Paned+PanedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.tblBitacora = new global::Gtk.TreeView ();
		this.tblBitacora.CanFocus = true;
		this.tblBitacora.Name = "tblBitacora";
		this.GtkScrolledWindow1.Add (this.tblBitacora);
		this.paned.Add (this.GtkScrolledWindow1);
		this.vbox4.Add (this.paned);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.paned]));
		w29.Position = 1;
		// Container child vbox4.Gtk.Box+BoxChild
		this.statusbar = new global::Gtk.Statusbar ();
		this.statusbar.Name = "statusbar";
		this.statusbar.Spacing = 6;
		this.vbox4.Add (this.statusbar);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.statusbar]));
		w30.Position = 2;
		w30.Expand = false;
		w30.Fill = false;
		this.Add (this.vbox4);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 638;
		this.DefaultHeight = 400;
		this.btndisconnect.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnconnect.Clicked += new global::System.EventHandler (this.OnBtnconnectClicked);
		this.btndisconnect.Clicked += new global::System.EventHandler (this.OnBtndisconnectClicked);
	}
}
