
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Image imgLogo;
	
	private global::Gtk.Label lblNotification;
	
	private global::Gtk.Image imgMain;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.WidthRequest = 1280;
		this.HeightRequest = 768;
		this.Name = "MainWindow";
		this.Title = "";
		this.TypeHint = ((global::Gdk.WindowTypeHint)(4));
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		this.Resizable = false;
		this.Decorated = false;
		this.Gravity = ((global::Gdk.Gravity)(10));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.imgLogo = new global::Gtk.Image ();
		this.imgLogo.Name = "imgLogo";
		this.vbox2.Add (this.imgLogo);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.imgLogo]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.lblNotification = new global::Gtk.Label ();
		this.lblNotification.Name = "lblNotification";
		this.lblNotification.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"#fff\" size=\"60000\" weight=\"normal\" style=\"normal\">¡¡¡Área de no" +
		"tificaciones!!!</span>");
		this.lblNotification.UseMarkup = true;
		this.vbox2.Add (this.lblNotification);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblNotification]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.imgMain = new global::Gtk.Image ();
		this.imgMain.Name = "imgMain";
		this.vbox2.Add (this.imgMain);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.imgMain]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1280;
		this.DefaultHeight = 768;
		this.Hide ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
