
// This file has been generated by the GUI designer. Do not modify.
namespace paySolution
{
	public partial class frmChangeScreen
	{
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.Label lblNotification;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Label lblPrint;
		
		private global::Gtk.Image imgMajor;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget paySolution.frmChangeScreen
			this.WidthRequest = 1280;
			this.HeightRequest = 768;
			this.Name = "paySolution.frmChangeScreen";
			this.Title = "";
			this.TypeHint = ((global::Gdk.WindowTypeHint)(4));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Resizable = false;
			this.Decorated = false;
			this.Gravity = ((global::Gdk.Gravity)(10));
			// Container child paySolution.frmChangeScreen.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			this.vbox7.BorderWidth = ((uint)(6));
			// Container child vbox7.Gtk.Box+BoxChild
			this.lblNotification = new global::Gtk.Label ();
			this.lblNotification.HeightRequest = 150;
			this.lblNotification.Name = "lblNotification";
			this.lblNotification.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"#fff\" size=\"40000\" weight=\"normal\" style=\"normal\">¡¡¡Área de no" +
			"tificaciones!!!</span>");
			this.lblNotification.UseMarkup = true;
			this.lblNotification.Justify = ((global::Gtk.Justification)(2));
			this.vbox7.Add (this.lblNotification);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.lblNotification]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.HeightRequest = 236;
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.lblPrint = new global::Gtk.Label ();
			this.lblPrint.Name = "lblPrint";
			this.lblPrint.Xalign = 1F;
			this.lblPrint.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"40000\">IMPRIMIR RECIBO</span>");
			this.lblPrint.UseMarkup = true;
			this.lblPrint.Justify = ((global::Gtk.Justification)(1));
			this.hbox8.Add (this.lblPrint);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.lblPrint]));
			w2.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.imgMajor = new global::Gtk.Image ();
			this.imgMajor.Name = "imgMajor";
			this.hbox8.Add (this.imgMajor);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.imgMajor]));
			w3.PackType = ((global::Gtk.PackType)(1));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox7.Add (this.hbox8);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox8]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.Add (this.vbox7);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1280;
			this.DefaultHeight = 768;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
