
// This file has been generated by the GUI designer. Do not modify.
namespace paySolution
{
	public partial class frmRenovation
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Alignment alignment3;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label lblVence;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Image imghborder1;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.Image imgvborder1;
		
		private global::Gtk.Label lblDataVence;
		
		private global::Gtk.Image imgvborder2;
		
		private global::Gtk.Image imghborder2;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label lblRenovar;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.Image imghborder3;
		
		private global::Gtk.HBox hbox10;
		
		private global::Gtk.Image imgvborder3;
		
		private global::Gtk.Label lblDataRenovar;
		
		private global::Gtk.Image imgvborder4;
		
		private global::Gtk.Image imghborder4;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label lblTotalPagar;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.Image imghborder5;
		
		private global::Gtk.HBox hbox11;
		
		private global::Gtk.Image imgvborder5;
		
		private global::Gtk.Label lblDataTotalPago;
		
		private global::Gtk.Image imgvborder6;
		
		private global::Gtk.Image imghborder6;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label lblVencera;
		
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.Image imghborder7;
		
		private global::Gtk.HBox hbox12;
		
		private global::Gtk.Image imgvborder7;
		
		private global::Gtk.Label lblDataPensionVencera;
		
		private global::Gtk.Image imgvborder8;
		
		private global::Gtk.Image imghborder8;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Image imgLogo;
		
		private global::Gtk.Alignment alignment2;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label lblPlus;
		
		private global::Gtk.Image imgMajor;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Label lblAcept;
		
		private global::Gtk.Image imgMajor1;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Label lblCancel;
		
		private global::Gtk.Image imgMajor2;
		
		private global::Gtk.HBox hbox13;
		
		private global::Gtk.Button button1;
		
		private global::Gtk.Button button3;
		
		private global::Gtk.Button button4;
		
		private global::Gtk.Alignment alignment1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget paySolution.frmRenovation
			this.WidthRequest = 1280;
			this.HeightRequest = 768;
			this.Name = "paySolution.frmRenovation";
			this.Title = "";
			this.TypeHint = ((global::Gdk.WindowTypeHint)(4));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.BorderWidth = ((uint)(3));
			this.Resizable = false;
			this.Decorated = false;
			this.Gravity = ((global::Gdk.Gravity)(10));
			// Container child paySolution.frmRenovation.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.HeightRequest = 5;
			this.alignment3.Name = "alignment3";
			this.vbox2.Add (this.alignment3);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment3]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Homogeneous = true;
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblVence = new global::Gtk.Label ();
			this.lblVence.Name = "lblVence";
			this.lblVence.Xalign = 1F;
			this.lblVence.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"35000\">Su pensión vence</span>");
			this.lblVence.UseMarkup = true;
			this.lblVence.Justify = ((global::Gtk.Justification)(1));
			this.hbox2.Add (this.lblVence);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lblVence]));
			w2.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.WidthRequest = 380;
			this.vbox4.Name = "vbox4";
			// Container child vbox4.Gtk.Box+BoxChild
			this.imghborder1 = new global::Gtk.Image ();
			this.imghborder1.Name = "imghborder1";
			this.vbox4.Add (this.imghborder1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.imghborder1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.imgvborder1 = new global::Gtk.Image ();
			this.imgvborder1.HeightRequest = 55;
			this.imgvborder1.Name = "imgvborder1";
			this.hbox9.Add (this.imgvborder1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.imgvborder1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.lblDataVence = new global::Gtk.Label ();
			this.lblDataVence.Name = "lblDataVence";
			this.lblDataVence.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.lblDataVence.UseMarkup = true;
			this.lblDataVence.Justify = ((global::Gtk.Justification)(2));
			this.hbox9.Add (this.lblDataVence);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.lblDataVence]));
			w5.Position = 1;
			// Container child hbox9.Gtk.Box+BoxChild
			this.imgvborder2 = new global::Gtk.Image ();
			this.imgvborder2.HeightRequest = 55;
			this.imgvborder2.Name = "imgvborder2";
			this.hbox9.Add (this.imgvborder2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.imgvborder2]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox4.Add (this.hbox9);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox9]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.imghborder2 = new global::Gtk.Image ();
			this.imghborder2.Name = "imghborder2";
			this.vbox4.Add (this.imghborder2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.imghborder2]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox2.Add (this.vbox4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox4]));
			w9.PackType = ((global::Gtk.PackType)(1));
			w9.Position = 1;
			w9.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w10.Position = 1;
			w10.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Homogeneous = true;
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblRenovar = new global::Gtk.Label ();
			this.lblRenovar.Name = "lblRenovar";
			this.lblRenovar.Xalign = 1F;
			this.lblRenovar.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"35000\">Renovar por meses</span>");
			this.lblRenovar.UseMarkup = true;
			this.lblRenovar.Justify = ((global::Gtk.Justification)(1));
			this.hbox3.Add (this.lblRenovar);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblRenovar]));
			w11.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.WidthRequest = 380;
			this.vbox5.Name = "vbox5";
			// Container child vbox5.Gtk.Box+BoxChild
			this.imghborder3 = new global::Gtk.Image ();
			this.imghborder3.Name = "imghborder3";
			this.vbox5.Add (this.imghborder3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.imghborder3]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.imgvborder3 = new global::Gtk.Image ();
			this.imgvborder3.HeightRequest = 55;
			this.imgvborder3.Name = "imgvborder3";
			this.hbox10.Add (this.imgvborder3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.imgvborder3]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.lblDataRenovar = new global::Gtk.Label ();
			this.lblDataRenovar.Name = "lblDataRenovar";
			this.lblDataRenovar.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.lblDataRenovar.UseMarkup = true;
			this.lblDataRenovar.Justify = ((global::Gtk.Justification)(2));
			this.hbox10.Add (this.lblDataRenovar);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.lblDataRenovar]));
			w14.Position = 1;
			// Container child hbox10.Gtk.Box+BoxChild
			this.imgvborder4 = new global::Gtk.Image ();
			this.imgvborder4.HeightRequest = 55;
			this.imgvborder4.Name = "imgvborder4";
			this.hbox10.Add (this.imgvborder4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.imgvborder4]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox5.Add (this.hbox10);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox10]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.imghborder4 = new global::Gtk.Image ();
			this.imghborder4.Name = "imghborder4";
			this.vbox5.Add (this.imghborder4);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.imghborder4]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.hbox3.Add (this.vbox5);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox5]));
			w18.PackType = ((global::Gtk.PackType)(1));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w19.Position = 2;
			w19.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Homogeneous = true;
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblTotalPagar = new global::Gtk.Label ();
			this.lblTotalPagar.Name = "lblTotalPagar";
			this.lblTotalPagar.Xalign = 1F;
			this.lblTotalPagar.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"35000\">Total a pagar</span>");
			this.lblTotalPagar.UseMarkup = true;
			this.lblTotalPagar.Justify = ((global::Gtk.Justification)(1));
			this.hbox4.Add (this.lblTotalPagar);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.lblTotalPagar]));
			w20.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.WidthRequest = 380;
			this.vbox6.Name = "vbox6";
			// Container child vbox6.Gtk.Box+BoxChild
			this.imghborder5 = new global::Gtk.Image ();
			this.imghborder5.Name = "imghborder5";
			this.vbox6.Add (this.imghborder5);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.imghborder5]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.imgvborder5 = new global::Gtk.Image ();
			this.imgvborder5.HeightRequest = 55;
			this.imgvborder5.Name = "imgvborder5";
			this.hbox11.Add (this.imgvborder5);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.imgvborder5]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.lblDataTotalPago = new global::Gtk.Label ();
			this.lblDataTotalPago.Name = "lblDataTotalPago";
			this.lblDataTotalPago.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.lblDataTotalPago.UseMarkup = true;
			this.lblDataTotalPago.Justify = ((global::Gtk.Justification)(2));
			this.hbox11.Add (this.lblDataTotalPago);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.lblDataTotalPago]));
			w23.Position = 1;
			// Container child hbox11.Gtk.Box+BoxChild
			this.imgvborder6 = new global::Gtk.Image ();
			this.imgvborder6.HeightRequest = 55;
			this.imgvborder6.Name = "imgvborder6";
			this.hbox11.Add (this.imgvborder6);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.imgvborder6]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			this.vbox6.Add (this.hbox11);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox11]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.imghborder6 = new global::Gtk.Image ();
			this.imghborder6.Name = "imghborder6";
			this.vbox6.Add (this.imghborder6);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.imghborder6]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			this.hbox4.Add (this.vbox6);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox6]));
			w27.PackType = ((global::Gtk.PackType)(1));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			this.vbox2.Add (this.hbox4);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
			w28.Position = 3;
			w28.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Homogeneous = true;
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.lblVencera = new global::Gtk.Label ();
			this.lblVencera.Name = "lblVencera";
			this.lblVencera.Xalign = 1F;
			this.lblVencera.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"35000\">Su pensión vencerá</span>");
			this.lblVencera.UseMarkup = true;
			this.lblVencera.Justify = ((global::Gtk.Justification)(1));
			this.hbox5.Add (this.lblVencera);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.lblVencera]));
			w29.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.WidthRequest = 380;
			this.vbox7.Name = "vbox7";
			// Container child vbox7.Gtk.Box+BoxChild
			this.imghborder7 = new global::Gtk.Image ();
			this.imghborder7.Name = "imghborder7";
			this.vbox7.Add (this.imghborder7);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.imghborder7]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.imgvborder7 = new global::Gtk.Image ();
			this.imgvborder7.HeightRequest = 55;
			this.imgvborder7.Name = "imgvborder7";
			this.hbox12.Add (this.imgvborder7);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.imgvborder7]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.lblDataPensionVencera = new global::Gtk.Label ();
			this.lblDataPensionVencera.Name = "lblDataPensionVencera";
			this.lblDataPensionVencera.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.lblDataPensionVencera.UseMarkup = true;
			this.lblDataPensionVencera.Justify = ((global::Gtk.Justification)(2));
			this.hbox12.Add (this.lblDataPensionVencera);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.lblDataPensionVencera]));
			w32.Position = 1;
			// Container child hbox12.Gtk.Box+BoxChild
			this.imgvborder8 = new global::Gtk.Image ();
			this.imgvborder8.HeightRequest = 55;
			this.imgvborder8.Name = "imgvborder8";
			this.hbox12.Add (this.imgvborder8);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.imgvborder8]));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			this.vbox7.Add (this.hbox12);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox12]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.imghborder8 = new global::Gtk.Image ();
			this.imghborder8.Name = "imghborder8";
			this.vbox7.Add (this.imghborder8);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.imghborder8]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			this.hbox5.Add (this.vbox7);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbox7]));
			w36.PackType = ((global::Gtk.PackType)(1));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			this.vbox2.Add (this.hbox5);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
			w37.Position = 4;
			w37.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w38.Position = 0;
			w38.Expand = false;
			w38.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.imgLogo = new global::Gtk.Image ();
			this.imgLogo.Name = "imgLogo";
			this.imgLogo.Xalign = 1F;
			this.vbox1.Add (this.imgLogo);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.imgLogo]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			w39.Padding = ((uint)(3));
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.HeightRequest = 139;
			this.alignment2.Name = "alignment2";
			this.vbox1.Add (this.alignment2);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment2]));
			w40.Position = 1;
			w40.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.HeightRequest = 150;
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.lblPlus = new global::Gtk.Label ();
			this.lblPlus.Name = "lblPlus";
			this.lblPlus.Xalign = 1F;
			this.lblPlus.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"60000\">+</span>");
			this.lblPlus.UseMarkup = true;
			this.lblPlus.Justify = ((global::Gtk.Justification)(1));
			this.hbox6.Add (this.lblPlus);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.lblPlus]));
			w41.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.imgMajor = new global::Gtk.Image ();
			this.imgMajor.CanFocus = true;
			this.imgMajor.Events = ((global::Gdk.EventMask)(512));
			this.imgMajor.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
			this.imgMajor.Name = "imgMajor";
			this.hbox6.Add (this.imgMajor);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.imgMajor]));
			w42.PackType = ((global::Gtk.PackType)(1));
			w42.Position = 1;
			w42.Expand = false;
			w42.Fill = false;
			this.vbox1.Add (this.hbox6);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
			w43.Position = 2;
			w43.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.HeightRequest = 150;
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.lblAcept = new global::Gtk.Label ();
			this.lblAcept.Name = "lblAcept";
			this.lblAcept.Xalign = 1F;
			this.lblAcept.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"60000\">ACEPTAR</span>");
			this.lblAcept.UseMarkup = true;
			this.lblAcept.Justify = ((global::Gtk.Justification)(1));
			this.hbox7.Add (this.lblAcept);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.lblAcept]));
			w44.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.imgMajor1 = new global::Gtk.Image ();
			this.imgMajor1.Name = "imgMajor1";
			this.hbox7.Add (this.imgMajor1);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.imgMajor1]));
			w45.PackType = ((global::Gtk.PackType)(1));
			w45.Position = 1;
			w45.Expand = false;
			w45.Fill = false;
			this.vbox1.Add (this.hbox7);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox7]));
			w46.Position = 3;
			w46.Expand = false;
			w46.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.HeightRequest = 150;
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.lblCancel = new global::Gtk.Label ();
			this.lblCancel.Name = "lblCancel";
			this.lblCancel.Xalign = 1F;
			this.lblCancel.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"60000\">CANCELAR</span>");
			this.lblCancel.UseMarkup = true;
			this.lblCancel.Justify = ((global::Gtk.Justification)(1));
			this.hbox8.Add (this.lblCancel);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.lblCancel]));
			w47.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.imgMajor2 = new global::Gtk.Image ();
			this.imgMajor2.Name = "imgMajor2";
			this.hbox8.Add (this.imgMajor2);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.imgMajor2]));
			w48.PackType = ((global::Gtk.PackType)(1));
			w48.Position = 1;
			w48.Expand = false;
			w48.Fill = false;
			this.vbox1.Add (this.hbox8);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox8]));
			w49.Position = 4;
			w49.Expand = false;
			w49.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("+");
			this.hbox13.Add (this.button1);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.button1]));
			w50.Position = 0;
			w50.Expand = false;
			w50.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString ("Aceptar");
			this.hbox13.Add (this.button3);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.button3]));
			w51.Position = 1;
			w51.Expand = false;
			w51.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button ();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.hbox13.Add (this.button4);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.button4]));
			w52.Position = 2;
			w52.Expand = false;
			w52.Fill = false;
			this.vbox1.Add (this.hbox13);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox13]));
			w53.Position = 5;
			w53.Expand = false;
			w53.Fill = false;
			this.hbox1.Add (this.vbox1);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
			w54.PackType = ((global::Gtk.PackType)(1));
			w54.Position = 1;
			w54.Expand = false;
			w54.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.WidthRequest = 25;
			this.alignment1.Name = "alignment1";
			this.hbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment1]));
			w55.PackType = ((global::Gtk.PackType)(1));
			w55.Position = 2;
			w55.Expand = false;
			w55.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1280;
			this.DefaultHeight = 768;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
			this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
			this.button4.Clicked += new global::System.EventHandler (this.OnButton4Clicked);
		}
	}
}
