
// This file has been generated by the GUI designer. Do not modify.
namespace paySolution
{
	public partial class frmNotificationsWin
	{
		private global::Gtk.VBox vbox10;
		
		private global::Gtk.Image imghborder1;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Image imgvborder1;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.Alignment alignment8;
		
		private global::Gtk.Image imgNotification;
		
		private global::Gtk.Alignment alignment6;
		
		private global::Gtk.Label lblNotification;
		
		private global::Gtk.Alignment alignment7;
		
		private global::Gtk.Image imgvborder2;
		
		private global::Gtk.Image imghborder2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget paySolution.frmNotificationsWin
			this.WidthRequest = 900;
			this.HeightRequest = 200;
			this.Name = "paySolution.frmNotificationsWin";
			this.Title = global::Mono.Unix.Catalog.GetString ("frmNotificationsWin");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(4));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			this.AcceptFocus = false;
			this.Decorated = false;
			this.DestroyWithParent = true;
			// Container child paySolution.frmNotificationsWin.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			// Container child vbox10.Gtk.Box+BoxChild
			this.imghborder1 = new global::Gtk.Image ();
			this.imghborder1.Name = "imghborder1";
			this.vbox10.Add (this.imghborder1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.imghborder1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			// Container child hbox8.Gtk.Box+BoxChild
			this.imgvborder1 = new global::Gtk.Image ();
			this.imgvborder1.Name = "imgvborder1";
			this.hbox8.Add (this.imgvborder1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.imgvborder1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			this.hbox9.BorderWidth = ((uint)(3));
			// Container child hbox9.Gtk.Box+BoxChild
			this.alignment8 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment8.WidthRequest = 10;
			this.alignment8.Name = "alignment8";
			this.hbox9.Add (this.alignment8);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.alignment8]));
			w3.Position = 0;
			w3.Expand = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.imgNotification = new global::Gtk.Image ();
			this.imgNotification.Name = "imgNotification";
			this.hbox9.Add (this.imgNotification);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.imgNotification]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment6.WidthRequest = 10;
			this.alignment6.HeightRequest = 0;
			this.alignment6.Name = "alignment6";
			this.hbox9.Add (this.alignment6);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.alignment6]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.lblNotification = new global::Gtk.Label ();
			this.lblNotification.Name = "lblNotification";
			this.lblNotification.LabelProp = global::Mono.Unix.Catalog.GetString ("String Notification");
			this.lblNotification.UseMarkup = true;
			this.lblNotification.Justify = ((global::Gtk.Justification)(2));
			this.hbox9.Add (this.lblNotification);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.lblNotification]));
			w6.Position = 3;
			// Container child hbox9.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment7.WidthRequest = 10;
			this.alignment7.Name = "alignment7";
			this.hbox9.Add (this.alignment7);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.alignment7]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 4;
			w7.Expand = false;
			this.hbox8.Add (this.hbox9);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.hbox9]));
			w8.Position = 1;
			// Container child hbox8.Gtk.Box+BoxChild
			this.imgvborder2 = new global::Gtk.Image ();
			this.imgvborder2.Name = "imgvborder2";
			this.hbox8.Add (this.imgvborder2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.imgvborder2]));
			w9.PackType = ((global::Gtk.PackType)(1));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox10.Add (this.hbox8);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox8]));
			w10.Position = 1;
			// Container child vbox10.Gtk.Box+BoxChild
			this.imghborder2 = new global::Gtk.Image ();
			this.imghborder2.Name = "imghborder2";
			this.vbox10.Add (this.imghborder2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.imghborder2]));
			w11.PackType = ((global::Gtk.PackType)(1));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.Add (this.vbox10);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 900;
			this.DefaultHeight = 200;
			this.Hide ();
		}
	}
}
