
// This file has been generated by the GUI designer. Do not modify.
namespace paySolution
{
	public partial class frmPayPanel
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Label lblRef;
		
		private global::Gtk.HBox hbox10;
		
		private global::Gtk.Button button1;
		
		private global::Gtk.Button button2;
		
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.Label lblTime;
		
		private global::Gtk.Label lblDate;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.Image imghborder;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label lblRef7;
		
		private global::Gtk.Label lblIngreso;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Label lblRef9;
		
		private global::Gtk.Label lblSalida;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.Label lblRef11;
		
		private global::Gtk.Label lblEstancia;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label lblRef1;
		
		private global::Gtk.Label lblTotal;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label lblRef2;
		
		private global::Gtk.Label lblPagado;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label lblRef3;
		
		private global::Gtk.Label lblChange;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Image imgLogo;
		
		private global::Gtk.Alignment alignment1;
		
		private global::Gtk.Label lblTotalPlus;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Label lblCancel;
		
		private global::Gtk.Image imgMajor;
		
		private global::Gtk.Alignment alignment4;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget paySolution.frmPayPanel
			this.WidthRequest = 1280;
			this.HeightRequest = 768;
			this.Name = "paySolution.frmPayPanel";
			this.Title = global::Mono.Unix.Catalog.GetString ("frmPayPanel");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(4));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Decorated = false;
			this.Gravity = ((global::Gdk.Gravity)(10));
			// Container child paySolution.frmPayPanel.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			this.hbox1.BorderWidth = ((uint)(6));
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblRef = new global::Gtk.Label ();
			this.lblRef.Name = "lblRef";
			this.lblRef.Xalign = 0F;
			this.lblRef.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"20000\">No. Pensión - 910002708</span>");
			this.lblRef.UseMarkup = true;
			this.vbox3.Add (this.lblRef);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblRef]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("Abonar");
			this.hbox10.Add (this.button1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.button1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.hbox10.Add (this.button2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.button2]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox3.Add (this.hbox10);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox10]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = -2;
			this.vbox7.BorderWidth = ((uint)(47));
			// Container child vbox7.Gtk.Box+BoxChild
			this.lblTime = new global::Gtk.Label ();
			this.lblTime.Name = "lblTime";
			this.lblTime.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"35000\">00:00:00</span>");
			this.lblTime.UseMarkup = true;
			this.vbox7.Add (this.lblTime);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.lblTime]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.lblDate = new global::Gtk.Label ();
			this.lblDate.Name = "lblDate";
			this.lblDate.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"25000\">Viernes 00 de Septiembre</span>");
			this.lblDate.UseMarkup = true;
			this.vbox7.Add (this.lblDate);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.lblDate]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox3.Add (this.vbox7);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox7]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			// Container child vbox5.Gtk.Box+BoxChild
			this.imghborder = new global::Gtk.Image ();
			this.imghborder.HeightRequest = 40;
			this.imghborder.Name = "imghborder";
			this.imghborder.Xalign = 0F;
			this.vbox5.Add (this.imghborder);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.imghborder]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.lblRef7 = new global::Gtk.Label ();
			this.lblRef7.WidthRequest = 200;
			this.lblRef7.Name = "lblRef7";
			this.lblRef7.Xalign = 1F;
			this.lblRef7.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"20000\">INGRESO</span>");
			this.lblRef7.UseMarkup = true;
			this.hbox6.Add (this.lblRef7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.lblRef7]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.lblIngreso = new global::Gtk.Label ();
			this.lblIngreso.Name = "lblIngreso";
			this.lblIngreso.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"30000\">00:00 a.m.</span>");
			this.lblIngreso.UseMarkup = true;
			this.hbox6.Add (this.lblIngreso);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.lblIngreso]));
			w10.Position = 1;
			this.vbox6.Add (this.hbox6);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox6]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.lblRef9 = new global::Gtk.Label ();
			this.lblRef9.WidthRequest = 200;
			this.lblRef9.Name = "lblRef9";
			this.lblRef9.Xalign = 1F;
			this.lblRef9.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"20000\">SALIDA</span>");
			this.lblRef9.UseMarkup = true;
			this.hbox7.Add (this.lblRef9);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.lblRef9]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.lblSalida = new global::Gtk.Label ();
			this.lblSalida.Name = "lblSalida";
			this.lblSalida.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"20000\">00:00 a.m.</span>");
			this.lblSalida.UseMarkup = true;
			this.hbox7.Add (this.lblSalida);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.lblSalida]));
			w13.Position = 1;
			this.vbox6.Add (this.hbox7);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox7]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.lblRef11 = new global::Gtk.Label ();
			this.lblRef11.WidthRequest = 200;
			this.lblRef11.Name = "lblRef11";
			this.lblRef11.Xalign = 1F;
			this.lblRef11.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"20000\">ESTANCIA</span>");
			this.lblRef11.UseMarkup = true;
			this.hbox9.Add (this.lblRef11);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.lblRef11]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.lblEstancia = new global::Gtk.Label ();
			this.lblEstancia.Name = "lblEstancia";
			this.lblEstancia.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"30000\">1 hra.</span>");
			this.lblEstancia.UseMarkup = true;
			this.hbox9.Add (this.lblEstancia);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.lblEstancia]));
			w16.Position = 1;
			this.vbox6.Add (this.hbox9);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox9]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox5.Add (this.vbox6);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vbox6]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox3.Add (this.vbox5);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox5]));
			w19.PackType = ((global::Gtk.PackType)(1));
			w19.Position = 3;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Homogeneous = true;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblRef1 = new global::Gtk.Label ();
			this.lblRef1.WidthRequest = 200;
			this.lblRef1.Name = "lblRef1";
			this.lblRef1.Xalign = 1F;
			this.lblRef1.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"20000\">TOTAL</span>");
			this.lblRef1.UseMarkup = true;
			this.hbox3.Add (this.lblRef1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblRef1]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblTotal = new global::Gtk.Label ();
			this.lblTotal.Name = "lblTotal";
			this.lblTotal.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"30000\">$ 000.00</span>");
			this.lblTotal.UseMarkup = true;
			this.hbox3.Add (this.lblTotal);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblTotal]));
			w21.Position = 1;
			this.vbox4.Add (this.hbox3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblRef2 = new global::Gtk.Label ();
			this.lblRef2.WidthRequest = 200;
			this.lblRef2.Name = "lblRef2";
			this.lblRef2.Xalign = 1F;
			this.lblRef2.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"20000\">PAGADO</span>");
			this.lblRef2.UseMarkup = true;
			this.hbox4.Add (this.lblRef2);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.lblRef2]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblPagado = new global::Gtk.Label ();
			this.lblPagado.Name = "lblPagado";
			this.lblPagado.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"30000\">$ 000.00</span>");
			this.lblPagado.UseMarkup = true;
			this.hbox4.Add (this.lblPagado);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.lblPagado]));
			w24.Position = 1;
			this.vbox4.Add (this.hbox4);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.lblRef3 = new global::Gtk.Label ();
			this.lblRef3.WidthRequest = 200;
			this.lblRef3.Name = "lblRef3";
			this.lblRef3.Xalign = 1F;
			this.lblRef3.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"20000\">CAMBIO</span>");
			this.lblRef3.UseMarkup = true;
			this.hbox5.Add (this.lblRef3);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.lblRef3]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.lblChange = new global::Gtk.Label ();
			this.lblChange.Name = "lblChange";
			this.lblChange.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"30000\">$ 000.00</span>");
			this.lblChange.UseMarkup = true;
			this.hbox5.Add (this.lblChange);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.lblChange]));
			w27.Position = 1;
			this.vbox4.Add (this.hbox5);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox5]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			this.vbox3.Add (this.vbox4);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox4]));
			w29.PackType = ((global::Gtk.PackType)(1));
			w29.Position = 4;
			w29.Expand = false;
			w29.Fill = false;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w30.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.WidthRequest = 434;
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.imgLogo = new global::Gtk.Image ();
			this.imgLogo.Name = "imgLogo";
			this.imgLogo.Xalign = 1F;
			this.vbox1.Add (this.imgLogo);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.imgLogo]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.HeightRequest = 127;
			this.alignment1.Name = "alignment1";
			this.vbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment1]));
			w32.Position = 1;
			w32.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblTotalPlus = new global::Gtk.Label ();
			this.lblTotalPlus.HeightRequest = 214;
			this.lblTotalPlus.Name = "lblTotalPlus";
			this.lblTotalPlus.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"90000\">$ 000.00</span>");
			this.lblTotalPlus.UseMarkup = true;
			this.lblTotalPlus.Justify = ((global::Gtk.Justification)(2));
			this.vbox1.Add (this.lblTotalPlus);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lblTotalPlus]));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.HeightRequest = 348;
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.lblCancel = new global::Gtk.Label ();
			this.lblCancel.Name = "lblCancel";
			this.lblCancel.Xalign = 1F;
			this.lblCancel.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"white\" size=\"60000\">CANCELAR</span>");
			this.lblCancel.UseMarkup = true;
			this.lblCancel.Justify = ((global::Gtk.Justification)(1));
			this.hbox8.Add (this.lblCancel);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.lblCancel]));
			w34.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.imgMajor = new global::Gtk.Image ();
			this.imgMajor.Name = "imgMajor";
			this.hbox8.Add (this.imgMajor);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.imgMajor]));
			w35.PackType = ((global::Gtk.PackType)(1));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox1.Add (this.hbox8);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox8]));
			w36.Position = 3;
			w36.Expand = false;
			w36.Fill = false;
			this.hbox1.Add (this.vbox1);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
			w37.PackType = ((global::Gtk.PackType)(1));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.WidthRequest = 62;
			this.alignment4.Name = "alignment4";
			this.hbox1.Add (this.alignment4);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment4]));
			w38.PackType = ((global::Gtk.PackType)(1));
			w38.Position = 2;
			w38.Expand = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1280;
			this.DefaultHeight = 768;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
			this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
		}
	}
}
