
// This file has been generated by the GUI designer. Do not modify.
namespace paySolution
{
	public partial class frmPublicity
	{
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Image imgPublicity;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget paySolution.frmPublicity
			this.WidthRequest = 1280;
			this.HeightRequest = 768;
			this.Name = "paySolution.frmPublicity";
			this.Title = "";
			this.TypeHint = ((global::Gdk.WindowTypeHint)(4));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Resizable = false;
			this.Decorated = false;
			this.Gravity = ((global::Gdk.Gravity)(10));
			// Container child paySolution.frmPublicity.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.imgPublicity = new global::Gtk.Image ();
			this.imgPublicity.Name = "imgPublicity";
			this.hbox2.Add (this.imgPublicity);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.imgPublicity]));
			w1.Position = 0;
			this.Add (this.hbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1280;
			this.DefaultHeight = 768;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
